"""add table image_analysis

Revision ID: 7f179b590ab3
Revises: c9f4c0ef8616
Create Date: 2026-05-02 19:13:47.479526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f179b590ab3'
down_revision: Union[str, Sequence[str], None] = 'c9f4c0ef8616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='processstatus', native_enum=False), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('viewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_analysis_s3_key'), 'image_analysis', ['s3_key'], unique=True)
    op.create_index(op.f('ix_image_analysis_user_id'), 'image_analysis', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_analysis_user_id'), table_name='image_analysis')
    op.drop_index(op.f('ix_image_analysis_s3_key'), table_name='image_analysis')
    op.drop_table('image_analysis')
    # ### end Alembic commands ###
