"""change name table

Revision ID: a34a888996a4
Revises: 4a4643600b03
Create Date: 2026-05-10 15:36:51.842320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34a888996a4'
down_revision: Union[str, Sequence[str], None] = '7f179b590ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('sugar', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=False),
    sa.Column('cholesterol', sa.Float(), nullable=False),
    sa.Column('sodium', sa.Float(), nullable=False),
    sa.Column('iron', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_nutrition_product_name'), 'products_nutrition', ['product_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        op.f('ix_products_nutrition_product_name'),
        table_name='products_nutrition'
    )
    op.drop_table('products_nutrition')
