import os
from dotenv import load_dotenv

load_dotenv()

NAME_DB = os.getenv("NAME_DB")
NAME_USER = os.getenv("NAME_USER")
PASSWORD_USER_DB = os.getenv("PASSWORD_USER_DB")
SECRET_KEY = os.getenv("SECRET_KEY")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))
REFRESH_TOKEN_EXPIRE_DAYS = int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS"))
APPLICATION_PASSWORD_GMAIL = os.getenv("APPLICATION_PASSWORD_GMAIL")
ALGORITHM = "HS256"
OAUTH2_GOOGLE_CLIENT_ID = os.getenv("OAUTH2_GOOGLE_CLIENT_ID")
OAUTH2_GOOGLE_CLIENT_SECRET = os.getenv("OAUTH2_GOOGLE_CLIENT_SECRET")
OAUTH2_GOOGLE_TOKEN_URL = os.getenv("OAUTH2_GOOGLE_TOKEN_URL")
MINIO_USER = os.getenv("MINIO_USER")
MINIO_PASSWORD = os.getenv("MINIO_PASSWORD")
MINIO_CURRENT_EXTERNAL_URL = os.getenv("MINIO_CURRENT_EXTERNAL_URL")
MINIO_CURRENT_INNER_URL = os.getenv("MINIO_CURRENT_INNER_URL")
RABBITMQ_CONNECT_URL = os.getenv("RABBITMQ_CONNECT_URL")